#!/bin/sh

if [ -e t1 ] ; then ( rm t1 ) ; fi
if [ -e t2 ] ; then ( rm t2 ) ; fi
if [ -e t3 ] ; then ( rm t3 ) ; fi

n=0
for file in DATA/* ; do

  net=`saclst knetwk f $file | awk '{print $2}'`
  sta=`saclst kstnm f $file | awk '{print $2}'`
  chan=`saclst kcmpnm f $file | awk '{print $2}'`
  #net=`echo $file | awk -F"." '{print $2}'`
  #sta=`echo $file | awk -F"." '{print $3}'`
  #chan=`echo $file | awk -F"." '{print $4}'`
  comp=`echo $chan | awk '{print substr($1,3,1)}'`
  #echo $net $sta $chan $comp

  # synthetics are always BH_
  #synt=SYN/${sta}.${net}.BH${comp}.semd.sac.d
  synt=`ls SYN/${sta}.${net}.BH${comp}*`
  out=MEASURE/${sta}.${net}.${chan}

  if [ -e $synt ] ; then

  b1=`saclst b f $file | awk '{print $2}'`
  b2=`saclst b f $synt | awk '{print $2}'`
  db=$(echo "sqrt(($b1 - $b2)^2)" | bc)
  dt1=`saclst delta f $file | awk '{print $2}'`
  dt2=`saclst delta f $synt | awk '{print $2}'`

    flag=`echo "$db 2*$dt1" | awk '{if ($1 < $2) print -1; else print 1}'`
    #if [ `echo "$dt1 - $dt2"| bc` = 0 ] ; then
       if [ $flag -lt 0 ] ; then
         n=`echo $n | awk '{print $n+1}'`
         echo $file >> t1
         echo $synt >> t1
         echo $out >> t1
       else
         echo $file >> t2
       fi

    #fi

  else
     echo $synt >> t3
  fi

done

# input file for window code
echo $n > input
cat t1 >> input
rm t1

# list of probable bad data files
rm input_bad
cat t2 >> input_bad
rm t2

# list of missing synthetic files
rm input_no_syn
cat t3 >> input_no_syn
rm t3









